title = "Fresh and Crispy"
baseURL = "https://blog.cpjobling.me"
languageCode = "en-GB"
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Dr Chris P. Jobling"
  favicon = "favicon.ico"
  site_logo = ""
  description = "More (or less) original insights from an old blogger"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/cpjobling"
  label = "Chris's GitHub account"
  color = "#ff6800"
